/*
 * To change this template, choose Tools | Templates
 * and open the template in the editor.
 */

/*
 * PartGui.java
 *
 * Created on 13-Mar-2010, 23:52:25
 */
import javax.swing.*;
import java.awt.*;
import java.awt.event.*;
import javax.swing.ImageIcon;
/**
 *
 * @author Administrator
 */
public class PartGui extends javax.swing.JFrame {

    // Variables declaration - do not modify
    private javax.swing.JButton okBut;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JSeparator jSeparator1;
    private javax.swing.JTextField pNameText;
    private javax.swing.JTextField pRoleText;
    // End of variables declaration
    
    private Xml xml = null;
    private int trackNo;
    private int partNo;
    private OkHandler oklis =null;
    private boolean tracklevel = false;
    private boolean isEdit = false;
    private int pos;
    private TrackGui track = null;
    private ProductGui prod = null;


    /** Creates new form PartGui */
    public PartGui() {
        initComponents();
    }

    /** This method is called from within the constructor to
     * initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is
     * always regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jLabel3 = new javax.swing.JLabel();
        pNameText = new javax.swing.JTextField();
        pRoleText = new javax.swing.JTextField();
        okBut = new javax.swing.JButton();
        jSeparator1 = new javax.swing.JSeparator();

        setDefaultCloseOperation(javax.swing.WindowConstants.DISPOSE_ON_CLOSE);
        setTitle("Add Participant - 7digital");

        jLabel1.setText("Add Participant");

        jLabel2.setText("Participant Name");

        jLabel3.setText("Participant Role");

        okBut.setText("OK");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jSeparator1, javax.swing.GroupLayout.DEFAULT_SIZE, 250, Short.MAX_VALUE)
                    .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jLabel1)
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel2)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(pNameText))
                        .addGroup(layout.createSequentialGroup()
                            .addComponent(jLabel3)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(okBut)
                                .addComponent(pRoleText, javax.swing.GroupLayout.PREFERRED_SIZE, 165, javax.swing.GroupLayout.PREFERRED_SIZE)))))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(jSeparator1, javax.swing.GroupLayout.PREFERRED_SIZE, 8, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(4, 4, 4)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel2)
                    .addComponent(pNameText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel3)
                    .addComponent(pRoleText, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(okBut)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        
        oklis = new OkHandler();
        okBut.addActionListener(oklis);        

        pack();
    }// </editor-fold>

    /**
    * @param args the command line arguments
    */
    public static void main(String args[]) {
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new PartGui().setVisible(true);
            }
        });
    }
    
    public void connect(Xml theXml, int tNo, boolean atTracklevel, TrackGui theTrack){
        xml = theXml;
        trackNo = tNo;
        if(atTracklevel == true){
            tracklevel =true;
            track = theTrack;
        }
    }
    
    public void setEdit(int thePos, int pNo){
        isEdit = true;
        pos = thePos;
        partNo = pNo;
        if(tracklevel ==false){
            pNameText.setText(xml.getParTagValue(pos,"participant_name"));
            pRoleText.setText(xml.getParTagValue(pos,"participant_role"));
        }
        else if(tracklevel ==true){
            pNameText.setText(xml.getTrackParticipentTagValue(pos,pNo,"participant_name"));
            pRoleText.setText(xml.getTrackParticipentTagValue(pos,pNo,"participant_role"));
        }
    }
        
    
    public void ProductLevelConnect(Xml theXml, ProductGui theProduct){
        prod = theProduct;
        }
    
    private class OkHandler implements ActionListener{
        
        public void actionPerformed(ActionEvent e){
            if(isEdit ==false){
                if(tracklevel ==true){
                    xml.addTrackParticipent(trackNo,pRoleText.getText(),pNameText.getText());
                    System.out.println(pNameText.getText() + "   " + pRoleText.getText());
                    track.updatePList(pRoleText.getText() + " - " + pNameText.getText());
                    //setVisible(false);
                   //dispose();
                }
                else{
                    xml.addParticipant(pRoleText.getText(), pNameText.getText());
                    System.out.println(pNameText.getText() + "   " + pRoleText.getText());
                    prod.updateParList(pNameText.getText() + " - " + pRoleText.getText());
                    //setVisible(false);
                    //dispose();
                }
            }
            else if(isEdit ==true){
                if(tracklevel ==true){
                    xml.editTrackParTagValue(pos,partNo,"participant_name",pNameText.getText());
                    xml.editTrackParTagValue(pos,partNo,"participant_role",pRoleText.getText());
                    track.updateParTInList(partNo,pNameText.getText() + " - " + pRoleText.getText());
                }
                else{
                    xml.editParTagValue(pos,"participant_name",pNameText.getText());
                    xml.editParTagValue(pos,"participant_role",pRoleText.getText());
                    prod.updatePartitleInList(pos, pNameText.getText() + " - " + pRoleText.getText());
                }
            }
            setVisible(false);
            dispose();
        }
    }
}
